

export const GET_FIRST_TWO_ARTICLES = "GET_FIRST_TWO_ARTICLES"
export const GET_OTHERS_ARTICLES = "GET_OTHERS_ARTICLES"
export const GRT_ARTICLE_BY_ID = "GRT_ARTICLE_BY_ID"
export const HANDLE_ARTICLE_LIKES = "HANDLE_ARTICLE_LIKES"
export const CLEAR_ARTICLE_DATA = "CLEAR_ARTICLE_DATA"